version: '3.9'

services:
  postgres:
    image: sicalo330/finalospostgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Agu4p4-nela
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4041:4041"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: npm run dev
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=prueba
      - DB_PASSWORD=Agu4p4-nela
      - DB_PORT=5432
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  postgres-data:
    driver: local

